[project]
name = "hanged_man"
version = "0.1.0"
description = "Hanged Man"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.11.13",
]
