[project]
name = "hanged_man"
version = "1.0.0"
description = "Un juego clásico del ahorcado implementado en Python con arquitectura hexagonal."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.11.13",
]
